//write the program to print the table
#include<iostream.h>
#include<conio.h>
main()
{
  int i,no1,no2;
  clrscr();
  cout<<"enter any number";
  cin>>no1;
  for(i=1;i<=10;i++)
  {
    cout<<"\n"<<no1<<"*"<<i<<"="<<no1*i;
    }

     cout<<"\n enterany number:-";
     cin>>no2;
     for(i=1;i<=10;i++)
     {
       cout<<"\n"<<no2<<"="<<i<<"="<<no2*i;
     }
     getch();
   }





